name: Publish cstrike-srcds Docker image

on:
  push:
    branches:
      - 'master'

jobs:
  push_to_registry:
    name: Build and push cstrike-srcds image to Docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./cstrike-srcds
          push: true
          tags: paulomu/cstrike-srcds:latest 
